import { bpost } from './api'

export const champions = [
  { id: -1, name: '无' },
  { id: 1, name: '黑暗之女' },
  { id: 2, name: '狂战士' },
  { id: 3, name: '正义巨像' },
  { id: 4, name: '卡牌大师' },
  { id: 5, name: '德邦总管' },
  { id: 6, name: '无畏战车' },
  { id: 7, name: '诡术妖姬' },
  { id: 8, name: '猩红收割者' },
  { id: 9, name: '远古恐惧' },
  { id: 10, name: '正义天使' },
  { id: 11, name: '无极剑圣' },
  { id: 12, name: '牛头酋长' },
  { id: 13, name: '符文法师' },
  { id: 14, name: '亡灵战神' },
  { id: 15, name: '战争女神' },
  { id: 16, name: '众星之子' },
  { id: 17, name: '迅捷斥候' },
  { id: 18, name: '麦林炮手' },
  { id: 19, name: '祖安怒兽' },
  { id: 20, name: '雪原双子' },
  { id: 21, name: '赏金猎人' },
  { id: 22, name: '寒冰射手' },
  { id: 23, name: '蛮族之王' },
  { id: 24, name: '武器大师' },
  { id: 25, name: '堕落天使' },
  { id: 26, name: '时光守护者' },
  { id: 27, name: '炼金术士' },
  { id: 28, name: '痛苦之拥' },
  { id: 29, name: '瘟疫之源' },
  { id: 30, name: '死亡颂唱者' },
  { id: 31, name: '虚空恐惧' },
  { id: 32, name: '殇之木乃伊' },
  { id: 33, name: '披甲龙龟' },
  { id: 34, name: '冰晶凤凰' },
  { id: 35, name: '恶魔小丑' },
  { id: 36, name: '祖安狂人' },
  { id: 37, name: '琴瑟仙女' },
  { id: 38, name: '虚空行者' },
  { id: 39, name: '刀锋舞者' },
  { id: 40, name: '风暴之怒' },
  { id: 41, name: '海洋之灾' },
  { id: 42, name: '英勇投弹手' },
  { id: 43, name: '天启者' },
  { id: 44, name: '瓦洛兰之盾' },
  { id: 45, name: '邪恶小法师' },
  { id: 48, name: '巨魔之王' },
  { id: 50, name: '诺克萨斯统领' },
  { id: 51, name: '皮城女警' },
  { id: 53, name: '蒸汽机器人' },
  { id: 54, name: '熔岩巨兽' },
  { id: 55, name: '不祥之刃' },
  { id: 56, name: '永恒梦魇' },
  { id: 57, name: '扭曲树精' },
  { id: 58, name: '荒漠屠夫' },
  { id: 59, name: '德玛西亚皇子' },
  { id: 60, name: '蜘蛛女皇' },
  { id: 61, name: '发条魔灵' },
  { id: 62, name: '齐天大圣' },
  { id: 63, name: '复仇焰魂' },
  { id: 64, name: '盲僧' },
  { id: 67, name: '暗夜猎手' },
  { id: 68, name: '机械公敌' },
  { id: 69, name: '魔蛇之拥' },
  { id: 72, name: '水晶先锋' },
  { id: 74, name: '大发明家' },
  { id: 75, name: '沙漠死神' },
  { id: 76, name: '狂野女猎手' },
  { id: 77, name: '兽灵行者' },
  { id: 78, name: '圣锤之毅' },
  { id: 79, name: '酒桶' },
  { id: 80, name: '不屈之枪' },
  { id: 81, name: '探险家' },
  { id: 82, name: '铁铠冥魂' },
  { id: 83, name: '牧魂人' },
  { id: 84, name: '离群之刺' },
  { id: 85, name: '狂暴之心' },
  { id: 86, name: '德玛西亚之力' },
  { id: 89, name: '曙光女神' },
  { id: 90, name: '虚空先知' },
  { id: 91, name: '刀锋之影' },
  { id: 92, name: '放逐之刃' },
  { id: 96, name: '深渊巨口' },
  { id: 98, name: '暮光之眼' },
  { id: 99, name: '光辉女郎' },
  { id: 101, name: '远古巫灵' },
  { id: 102, name: '龙血武姬' },
  { id: 103, name: '九尾妖狐' },
  { id: 104, name: '法外狂徒' },
  { id: 105, name: '潮汐海灵' },
  { id: 106, name: '不灭狂雷' },
  { id: 107, name: '傲之追猎者' },
  { id: 110, name: '惩戒之箭' },
  { id: 111, name: '深海泰坦' },
  { id: 112, name: '机械先驱' },
  { id: 113, name: '北地之怒' },
  { id: 114, name: '无双剑姬' },
  { id: 115, name: '爆破鬼才' },
  { id: 117, name: '仙灵女巫' },
  { id: 119, name: '荣耀行刑官' },
  { id: 120, name: '战争之影' },
  { id: 121, name: '虚空掠夺者' },
  { id: 122, name: '诺克萨斯之手' },
  { id: 126, name: '未来守护者' },
  { id: 127, name: '冰霜女巫' },
  { id: 131, name: '皎月女神' },
  { id: 133, name: '德玛西亚之翼' },
  { id: 134, name: '暗黑元首' },
  { id: 136, name: '铸星龙王' },
  { id: 141, name: '影流之镰' },
  { id: 142, name: '暮光星灵' },
  { id: 143, name: '荆棘之兴' },
  { id: 145, name: '虚空之女' },
  { id: 147, name: '星籁歌姬' },
  { id: 150, name: '迷失之牙' },
  { id: 154, name: '生化魔人' },
  { id: 157, name: '疾风剑豪' },
  { id: 161, name: '虚空之眼' },
  { id: 163, name: '岩雀' },
  { id: 164, name: '青钢影' },
  { id: 166, name: '影哨' },
  { id: 201, name: '弗雷尔卓德之心' },
  { id: 202, name: '戏命师' },
  { id: 203, name: '永猎双子' },
  { id: 221, name: '祖安花火' },
  { id: 222, name: '暴走萝莉' },
  { id: 223, name: '河流之王' },
  { id: 234, name: '破败之王' },
  { id: 235, name: '涤魂圣枪' },
  { id: 236, name: '圣枪游侠' },
  { id: 238, name: '影流之主' },
  { id: 240, name: '暴怒骑士' },
  { id: 245, name: '时间刺客' },
  { id: 246, name: '元素女皇' },
  { id: 254, name: '皮城执法官' },
  { id: 266, name: '暗裔剑魔' },
  { id: 267, name: '唤潮鲛姬' },
  { id: 268, name: '沙漠皇帝' },
  { id: 350, name: '魔法猫咪' },
  { id: 360, name: '沙漠玫瑰' },
  { id: 412, name: '魂锁典狱长' },
  { id: 420, name: '海兽祭司' },
  { id: 421, name: '虚空遁地兽' },
  { id: 427, name: '翠神' },
  { id: 429, name: '复仇之矛' },
  { id: 432, name: '星界游神' },
  { id: 497, name: '幻翎' },
  { id: 498, name: '逆羽' },
  { id: 516, name: '山隐之焰' },
  { id: 517, name: '解脱者' },
  { id: 518, name: '万花通灵' },
  { id: 523, name: '残月之肃' },
  { id: 526, name: '镕铁少女' },
  { id: 555, name: '血港鬼影' },
  { id: 711, name: '愁云使者' },
  { id: 777, name: '封魔剑魂' },
  { id: 875, name: '腕豪' },
  { id: 876, name: '含羞蓓蕾' },
  { id: 887, name: '灵罗娃娃' },
  { id: 888, name: '炼金男爵' },
]

export interface Config {
  autoAcceptGame: boolean
  autoPickChampID: number
  autoBanChampID: number
  autoSendTeamHorse: boolean
  shouldSendSelfHorse: boolean
  horseNameConf: string[]
  chooseSendHorseMsg: boolean[]
  chooseChampSendMsgDelaySec: number
  shouldInGameSaveMsgToClipBoard: boolean
}
export interface HorseInfo {
  horse: string
  score: number
  currKDA: string[]
}
export function getAllConfig() {
  return bpost<Config>({
    url: '/v1/config/getAll',
  })
}
export function updateConfig(data: Config) {
  return bpost({
    url: '/v1/config/update',
    data,
  })
}
export function querySummonerScore(name: string) {
  return bpost<HorseInfo>({
    url: '/v1/config/update',
    data: {
      summonerName: name,
    },
  })
}
