export const baseUrl = 'http://localhost:4396'
export const apiUrl = baseUrl
export const withCredentials = false
export const projectName = 'lol对局先知'
export const routeBaseName = '/'
export const localStoragePrefix = 'hh-lol-prophet'
export const bilibiliVideoUrl = "https://www.bilibili.com/video/BV1A34y117kh"
export const projectGhUrl = "https://github.com/real-web-world/hh-lol-prophet"
export const projectQQGroup = "102158075"
export const defaultDlUrl = "https://k-static.buffge.com:40012/s/hh-lol-prophet/v0.2.5/hh-lol-prophet-v0.2.5.zip"
export const defaultVersionTag = "v0.2.5"
export const lolApiBaseUrl = import.meta.env.VITE_LOL_API_BASE_URL ?? "https://k2-api.buffge.com:40012/prod/lol"
export const faroUrl = "https://faro-collector-prod-ap-southeast-1.grafana.net/collect/22761c80bcc128c9dea43a1e9824d230"
export const faroAppName = "lol.buffge.com"
